name: Update Submodules

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Update submodules
        run: |
          git submodule update --remote --recursive
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git commit -am "Update submodules"
          git push